# Generated by Django 6.0.1 on 2026-01-27 16:55

import apps.certificado.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Dirección/Gestión')),
                ('codigo', models.CharField(help_text='Código corto para identificación (ej: DV, DAC)', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Solo las direcciones activas aparecen en formularios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Dirección/Gestión',
                'verbose_name_plural': 'Direcciones/Gestiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Modalidad')),
                ('nombre_evento', models.CharField(max_length=300, verbose_name='Nombre del Evento')),
                ('duracion_horas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (horas)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('taller', 'Taller'), ('seminario', 'Seminario'), ('conferencia', 'Conferencia'), ('capacitacion', 'Capacitación'), ('diplomado', 'Diplomado'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('tipo_evento', models.CharField(help_text='Descripción específica del tipo de evento', max_length=200, verbose_name='Tipo de Evento')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('objetivo_programa', models.TextField(verbose_name='Objetivo del Programa')),
                ('contenido_programa', models.TextField(verbose_name='Contenido del Programa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='certificado.direccion', verbose_name='Dirección/Gestión')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_completos', models.CharField(max_length=300, verbose_name='Nombres Completos')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='certificado.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombres_completos'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_docx', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.certificado_docx_path, verbose_name='Archivo DOCX Generado')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=apps.certificado.models.certificado_pdf_path, verbose_name='Archivo PDF Generado')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('sending_email', 'Enviando Email'), ('sent', 'Enviado')], default='pending', max_length=20, verbose_name='Estado')),
                ('enviado_email', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('intentos_envio', models.PositiveIntegerField(default=0, verbose_name='Intentos de Envío')),
                ('error_mensaje', models.TextField(blank=True, help_text='Detalles del error si la generación falló', verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='certificado.estudiante', verbose_name='Estudiante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='certificado.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('archivo', models.FileField(help_text='Plantilla con variables {{VARIABLE}}', upload_to=apps.certificado.models.plantilla_base_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Archivo Word (.docx)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_activa', models.BooleanField(default=True, help_text='Solo una plantilla activa por dirección', verbose_name='Es Activa')),
                ('variables_disponibles', models.JSONField(blank=True, default=list, help_text='Lista de variables encontradas en la plantilla', verbose_name='Variables Disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_base', to='certificado.direccion', verbose_name='Dirección/Gestión')),
            ],
            options={
                'verbose_name': 'Plantilla Base',
                'verbose_name_plural': 'Plantillas Base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estudiantes', models.PositiveIntegerField(default=0, verbose_name='Total de Estudiantes')),
                ('procesados', models.PositiveIntegerField(default=0, verbose_name='Procesados')),
                ('exitosos', models.PositiveIntegerField(default=0, verbose_name='Exitosos')),
                ('fallidos', models.PositiveIntegerField(default=0, verbose_name='Fallidos')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcialmente Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procesamiento_lote', to='certificado.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Procesamiento en Lote',
                'verbose_name_plural': 'Procesamientos en Lote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantePlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Con Logo Grande, Modalidad Virtual', max_length=200, verbose_name='Nombre de la Variante')),
                ('archivo', models.FileField(help_text='Variante de la plantilla base', upload_to=apps.certificado.models.variante_plantilla_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Archivo Word (.docx)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el selector', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Solo las variantes activas aparecen en formularios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('plantilla_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='certificado.plantillabase', verbose_name='Plantilla Base')),
            ],
            options={
                'verbose_name': 'Variante de Plantilla',
                'verbose_name_plural': 'Variantes de Plantillas',
                'ordering': ['plantilla_base', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='plantilla_seleccionada',
            field=models.ForeignKey(blank=True, help_text='Si no se selecciona, se usa la plantilla base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='certificado.varianteplantilla', verbose_name='Variante de Plantilla Seleccionada'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('evento', 'correo_electronico'), name='unique_estudiante_por_evento'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['evento', 'estado'], name='certificado_evento__16fca3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['estudiante'], name='certificado_estudia_b9a3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['estado'], name='certificado_estado_4738e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='plantillabase',
            constraint=models.UniqueConstraint(condition=models.Q(('es_activa', True)), fields=('direccion',), name='unique_active_plantilla_per_direccion'),
        ),
    ]
