# Generated by Django 6.0.1 on 2026-01-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Modalidad')),
                ('codigo', models.CharField(help_text='Código corto (ej: VIR, PRE, HIB)', max_length=20, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, help_text='Solo las modalidades activas aparecen en formularios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('codigo', models.CharField(help_text='Código corto (ej: CUR, TAL, SEM)', max_length=20, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, help_text='Solo los tipos activos aparecen en formularios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Descripción del Tipo de Evento')),
                ('codigo', models.CharField(help_text='Código corto', max_length=20, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, help_text='Solo los tipos activos aparecen en formularios', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion_horas',
            field=models.CharField(help_text='Ej: 40 horas, 3 días', max_length=100, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='certificado.modalidad', verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='certificado.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(help_text='Descripción específica del tipo de evento', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='certificado.tipoevento', verbose_name='Tipo de Evento'),
        ),
    ]
