# Generated by Django 6.0.1 on 2026-01-24 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso_fecha_fin_curso_fecha_inicio_curso_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estado',
        ),
        migrations.AlterField(
            model_name='curso',
            name='archivo_estudiantes',
            field=models.FileField(help_text='Subir archivo con columnas: Nombres, Cedula, Correo', upload_to='cursos/estudiantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='Archivo de Estudiantes (Excel)'),
        ),
    ]
