# Generated by Django 6.0.1 on 2026-01-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_curso_estado_alter_curso_archivo_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='configuracion_certificado',
            field=models.JSONField(blank=True, help_text='Almacena posiciones, fuentes y texto dinámico.', null=True, verbose_name='Configuración del Certificado'),
        ),
    ]
