# Generated by Django 6.0.1 on 2026-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_curso_configuracion_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='texto_certificado',
            field=models.TextField(blank=True, help_text='Contenido del certificado. Use {NOMBRE_ESTUDIANTE}, {CEDULA}, {CURSO}, {FECHA_INICIO}, {FECHA_FIN}, {RESPONSABLE} como variables.', null=True, verbose_name='Texto del Certificado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='responsable',
            field=models.CharField(default='', max_length=200, verbose_name='Responsable del curso'),
            preserve_default=False,
        ),
    ]
