# Generated by Django 6.0.1 on 2026-01-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_curso_texto_certificado_alter_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('oculto', 'Oculto'), ('archivado', 'Archivado')], default='disponible', help_text='Estado del curso en el portal público', max_length=20, verbose_name='Estado'),
        ),
    ]
