# Generated by Django 6.0.1 on 2026-01-25 21:38

import apps.curso.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_curso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo_generado',
            field=models.FileField(blank=True, null=True, upload_to=apps.curso.models.certificate_directory_path, verbose_name='Certificado Generado'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo_verificacion',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Código de Verificación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nombre del curso'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['codigo_verificacion'], name='curso_certi_codigo__1d2620_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['estudiante'], name='curso_certi_estudia_a81c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['plantilla'], name='curso_certi_plantil_824a31_idx'),
        ),
    ]
