# Generated by Django 6.0.1 on 2026-01-26 16:08

import apps.curso.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_alter_certificado_archivo_generado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='access_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de accesos'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Acceso público'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='last_access',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último acceso'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo_verificacion',
            field=models.CharField(db_index=True, default=apps.curso.models.generate_verification_code, max_length=50, unique=True, verbose_name='Código de Verificación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='archivo_estudiantes',
            field=models.FileField(help_text='Subir archivo con columnas: Nombres, Cedula, Correo', upload_to=apps.curso.models.estudiantes_excel_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='Archivo de Estudiantes (Excel)'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='archivo',
            field=models.FileField(upload_to=apps.curso.models.plantilla_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Archivo de plantilla'),
        ),
    ]
